"use client";
import { FormEvent, useState } from "react";

const services = [
  ["01", "Websites that do a job", "Fast, polished sites designed to turn local searches and referrals into real enquiries."],
  ["02", "Business automation", "Remove repetitive admin with practical workflows tailored to the way your team already works."],
  ["03", "Custom software", "Quoting tools, client portals, booking systems and internal apps built around your business."],
];
const steps = [["Discover","We map the bottleneck and what success looks like."],["Design","You see the direction early, before the full build."],["Build","Your software is developed, tested and refined."],["Launch","We put it live and stay available after handover."]];

export default function Home(){
 const [sent,setSent]=useState(false);
 function quote(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent(`Quote request from ${d.get("name")}`);const body=encodeURIComponent(`Name: ${d.get("name")}\nBusiness: ${d.get("business")}\nEmail: ${d.get("email")}\nProject: ${d.get("project")}\n\n${d.get("details")}`);setSent(true);window.location.href=`mailto:hello@syedsoftware.com.au?subject=${subject}&body=${body}`}
 return <main>
  <header><a className="brand" href="#top"><b><i/><i/><i/></b><span>SYED<small>SOFTWARE</small></span></a><nav><a href="#services">Services</a><a href="#process">Process</a><a className="navCta" href="#quote">Request a quote ↗</a></nav></header>
  <section className="hero" id="top"><div><p className="eyebrow"><i/> SOFTWARE FOR LOCAL BUSINESS</p><h1>Your business has a <em>better way</em> to work.</h1><p className="lead">Syed Software builds websites, automations and custom tools that save local businesses time—and help them win more customers.</p><div className="actions"><a className="primary" href="#quote">Request a quote <span>↗</span></a><a href="#services">See what we build ↓</a></div><div className="trust"><span>Built locally</span><span>Clear fixed scopes</span><span>Direct developer access</span></div></div>
  <div className="board"><div className="boardTop"><span>BUSINESS.OS</span><span>● LIVE</span></div><div className="card"><small>NEW LEAD</small><strong>Website enquiry</strong><i>Just now</i></div><div className="line">···</div><div className="card mid"><small>AUTOMATION</small><strong>Quote drafted</strong><i>Admin time saved</i></div><div className="line">···</div><div className="card end"><small>RESULT</small><strong>Job confirmed</strong><i>Customer notified</i></div><div className="boardFoot"><small>ONE CONNECTED SYSTEM</small><strong>Less admin.<br/>More business.</strong><b><i/><i/></b></div></div></section>
  <div className="ticker">WEBSITES ✦ AUTOMATION ✦ CUSTOM SOFTWARE ✦ CLIENT PORTALS ✦ BOOKING SYSTEMS ✦</div>
  <section className="services section" id="services"><div className="intro"><small>WHAT WE BUILD</small><h2>Useful software.<br/><em>Nothing you don’t need.</em></h2><p>No bloated platforms or vague tech talk. Just the right solution for the problem slowing your business down.</p></div><div className="serviceList">{services.map(([n,t,p])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div><b>↗</b></article>)}</div></section>
  <section className="statement"><div><small>BUILT FOR THE REAL WORLD</small><h2>Software should fit your business.<br/><em>Not the other way around.</em></h2></div><p>You know your business. We know how to turn the frustrating, manual parts into something faster, simpler and easier to grow.</p></section>
  <section className="section process" id="process"><div className="intro"><small>HOW IT WORKS</small><h2>From problem to <em>working product.</em></h2></div><div className="steps">{steps.map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
  <section className="quote" id="quote"><div><small>START A PROJECT</small><h2>What could work <em>better</em> in your business?</h2><p>Tell us what you’re trying to improve. We’ll reply with practical next steps—not a hard sell.</p><div className="reply">↳ <b>Typically replies within 1 business day</b></div></div><form onSubmit={quote}><div className="row"><label>Your name<input name="name" placeholder="e.g. Sarah Nguyen" required/></label><label>Business name<input name="business" placeholder="Your business" required/></label></div><label>Email address<input name="email" type="email" placeholder="you@business.com" required/></label><label>What do you need?<select name="project" defaultValue=""><option value="" disabled>Select a project type</option><option>Business website</option><option>Automation</option><option>Custom software</option><option>Not sure yet</option></select></label><label>Tell us about the project<textarea name="details" rows={4} placeholder="What problem are you trying to solve?" required/></label><button>Request my quote <span>↗</span></button>{sent&&<p className="note">Your email app should now open with the enquiry ready.</p>}</form></section>
  <footer><a className="brand" href="#top"><b><i/><i/><i/></b><span>SYED<small>SOFTWARE</small></span></a><p>Practical software for ambitious local businesses.</p><a href="#top">Back to top ↑</a></footer>
 </main>
}
